<!DOCTYPE html>
<html>
<head>
	<title>BOOKING</title>
	<meta name="viewport" content="width=device-width">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="inner-page-style.css">
	<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
	<div id="page" class="site">
		<header class="site-header">
			<div class="top-header">
				<div class="container">
					<div class="top-header-left">
						<div class="top-header-block">
							<a href="mailto:info@educationpro.com"><i class="fas fa-envelope"></i> LET'STRAVEL@gmail.com</a>
						</div>
						<div class="top-header-block">
							<a href="tel:+9779813639131"><i class="fas fa-phone"></i> +977 9813639131</a>
						</div>
					</div>
					<div class="top-header-right">
						<div class="social-block">
							<ul class="social-list">
								<li><a href=""><i class="fab fa-viber"></i></a></li>
								<li><a href=""><i class="fab fa-google-plus-g"></i></a></li>
								<li><a href=""><i class="fab fa-facebook-square"></i></a></li>
								<li><a href=""><i class="fab fa-facebook-messenger"></i></a></li>
								<li><a href=""><i class="fab fa-twitter"></i></a></li>
								<li><a href=""><i class="fab fa-skype"></i></a></li>
							</ul>
						</div>
						<div class="login-block">
							<a href="login.php">Login /</a>
							<a href="register.php">Register</a>
						</div>
					</div>
				</div>
			</div>
			<div class="main-header">
				<div class="container">
					<div class="logo-wrap">
						<img src="C:\Users\IMAD\Desktop\final  agency\_dc828ef2-b734-4736-ad2f-274d8c1748a6.jpeg" height="150" width="150" alt="Logo Image">
					</div>
					<div class="nav-wrap">
						<nav class="nav-desktop">
							<ul class="menu-list">
								<li><a href="home.php">Home</a></li>
								<li><a href="destination.php">Destination</a></li>
								<li><a href="booking.php">BOOKING</a></li>
								<li><a href="testimonials.php">Testimonials</a></li>
							</ul>
						</nav>
						<div id="bar">
							<i class="fas fa-bars"></i>
						</div>
						<div id="close">
							<i class="fas fa-times"></i>
						</div>
					</div>
				</div>
			</div>
		</header>
	
			
			
		
		<section class="contact-page-section">
			<div class="container">
				<div class="people-info-wrap">
					<h2>Please enter your information</h2>
					
					<form>
						<span>
						<input type="text" placeholder="Full Name*" class="input- name">
						<input type="email" placeholder="Email*" class="input- email">
						</span>
						<label for="offers" id="lab">Choose :</label>
                    <select name="of" id="of">
                         <option value="NY">NEW YORK_USA</option>
                          <option value="TK">TOKYO_JAPAN</option>
                          <option value="VN">VIENNA_AUSTRIA</option>
                          <option value="QU">QUEBEC City _CANADA_</option>
                    </select>
							
						</textarea>
						<input type="submit" value="submit now">
					</form>
				</div>

				<div class="contact-info">
					<h2>contact info</h2>
					<ul class="contact-list">
						<li><i class="fas fa-location-arrow"></i> 
							<span>
								<p>MOROCCO</p>
							    
							</span>
						</li>
						<li><i class="fas fa-phone"></i>
							<span> 
								<p>Phone: 016204888, Mobile: 9813639131</p>
								<p>Fax:7838478387</p>
							</span>
						</li>
						<li><i class="fas fa-envelope"></i>
							<span>
								<p>LET'STRAVEL@gmail.com</p>
							</span>
						</li>
					</ul>
					<ul class="contact-social">
						<li><a href=""><i class="fab fa-viber"></i></a></li>
						<li><a href=""><i class="fab fa-google-plus-g"></i></a></li>
						<li><a href=""><i class="fab fa-facebook-square"></i></a></li>
						<li><a href=""><i class="fab fa-facebook-messenger"></i></a></li>
						<li><a href=""><i class="fab fa-twitter"></i></a></li>
						<li><a href=""><i class="fab fa-skype"></i></a></li>
						<li><a href=""><i class="fab fa-youtube"></i></a></li>
					</ul>
				</div>
			</div>
		</section>

		<section class="map-section">
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2637832.0087765665!2d-7.054781523445791!3d33.826278716568964!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd0b88619651c58d%3A0xd9d39381c42cffc3!2sMorocco!5e0!3m2!1sen!2sma!4v1715787820827!5m2!1sen!2sma" width="1480" height="600" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
		</section>

		<section class="query-section">
			<div class="container">
				<p>Any Queries? Ask us a question at<a href="tel:+9779813639131"><i class="fas fa-phone"></i> +977 9813639131</a></p>
			</div>
		</section>
		<footer class="page-footer">
			<div class="footer-first-section">
				<div class="container">
					<div class="box-wrap">
						<header>
							<h1>about</h1>
						</header>
						<p>"Explore new worlds, embrace diverse cultures, create memories that last a lifetime."</p>

						<h4><a href="tel:+9779813639131"><i class="fas fa-phone"></i> +977 9813639131</a></h4>
						<h4><a href="mailto:info@educationpro.com"><i class="fas fa-envelope"></i> LET'STRAVEL@gmail.com</a></h4>
						<h4><i class="fas fa-map-marker-alt"></i>MORROCO</h4>
					</div>

					<div class="box-wrap">
						<header>
							<h1>links</h1>
						</header>
						<ul>
							<li><a href="home.php">home</a></li>
							<li><a href="destination.php">DESTINATION</a></li>
							<li><a href="booking.php">BOOKING</a></li>
							<li><a href="testimonials.php">Testimonials</a></li>
						</ul>
					</div>

					

					<div class="box-wrap">
						<header>
							<h1>quick contact</h1>
						</header>
						<section class="quick-contact">
							<input type="email" name="email" placeholder="Your Email*">
							<textarea placeholder="Type your message*"></textarea>
							<button>send message</button>
						</section>
					</div>

				</div>
			</div>
			<div class="footer-second-section">
				<div class="container">
					<hr class="footer-line">
					<ul class="social-list">
						<li><a href=""><i class="fab fa-facebook-square"></i></a></li>
						<li><a href=""><i class="fab fa-twitter"></i></a></li>
						<li><a href=""><i class="fab fa-skype"></i></a></li>
						<li><a href=""><i class="fab fa-youtube"></i></a></li>
						<li><a href=""><i class="fab fa-instagram"></i></a></li>
					</ul>
					<hr class="footer-line">
				</div>
			</div>
			<div class="footer-last-section">
				<div class="container">
					<p>LET'S TRAVEL</p>
				</div>
			</div>
		</footer>
	</div>
	
</body>
</html>